server:
  port: 9001

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  allowed:
    resources: /h2/**
  security:
    basic:
      enabled: true
      authorize-mode: NONE

logging:
  level:
    org:
      springframework: TRACE
    com:
      mchu: TRACE
